/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { BamlRuntime, FunctionResult, BamlCtxManager, ClientRegistry, Image, Audio } from "@boundaryml/baml"
import { toBamlError, BamlStream } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {Analysis, CashFlow, CostOfRevenue, Costs, Deltas, EBITDA, Expenses, Experience, FinancialMetrics, FinancialMetricsEBITDA, Formula, GrossProfit, MissingParam, MonthlyComparison, Name, PerShare, Profitability, ProformaMetrics, Resume, Revenue} from "./types"
import type TypeBuilder from "./type_builder"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

export class BamlAsyncClient {
  private runtime: BamlRuntime
  private ctx_manager: BamlCtxManager
  private stream_client: BamlStreamClient

  constructor(runtime: BamlRuntime, ctx_manager: BamlCtxManager) {
    this.runtime = runtime
    this.ctx_manager = ctx_manager
    this.stream_client = new BamlStreamClient(runtime, ctx_manager)
  }

  get stream() {
    return this.stream_client
  }

  
  async AnalyzeFinancials(
      data: Image,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<FinancialMetricsEBITDA[]> {
    try {
      const raw = await this.runtime.callFunction(
        "AnalyzeFinancials",
        {
          "data": data
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as FinancialMetricsEBITDA[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async AnalyzeProforma(
      data: Image,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<Analysis> {
    try {
      const raw = await this.runtime.callFunction(
        "AnalyzeProforma",
        {
          "data": data
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as Analysis
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async ExtractResume(
      resume: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<Resume> {
    try {
      const raw = await this.runtime.callFunction(
        "ExtractResume",
        {
          "resume": resume
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as Resume
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  async GetMissingParams(
      params: string[],analysis: Analysis,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): Promise<MissingParam[]> {
    try {
      const raw = await this.runtime.callFunction(
        "GetMissingParams",
        {
          "params": params,"analysis": analysis
        },
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return raw.parsed(false) as MissingParam[]
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

class BamlStreamClient {
  constructor(private runtime: BamlRuntime, private ctx_manager: BamlCtxManager) {}

  
  AnalyzeFinancials(
      data: Image,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<(partial_types.FinancialMetricsEBITDA | null)[], FinancialMetricsEBITDA[]> {
    try {
      const raw = this.runtime.streamFunction(
        "AnalyzeFinancials",
        {
          "data": data
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<(partial_types.FinancialMetricsEBITDA | null)[], FinancialMetricsEBITDA[]>(
        raw,
        (a): (partial_types.FinancialMetricsEBITDA | null)[] => a,
        (a): FinancialMetricsEBITDA[] => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  AnalyzeProforma(
      data: Image,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.Analysis, Analysis> {
    try {
      const raw = this.runtime.streamFunction(
        "AnalyzeProforma",
        {
          "data": data
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.Analysis, Analysis>(
        raw,
        (a): partial_types.Analysis => a,
        (a): Analysis => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  ExtractResume(
      resume: string,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<partial_types.Resume, Resume> {
    try {
      const raw = this.runtime.streamFunction(
        "ExtractResume",
        {
          "resume": resume
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<partial_types.Resume, Resume>(
        raw,
        (a): partial_types.Resume => a,
        (a): Resume => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
  GetMissingParams(
      params: string[],analysis: Analysis,
      __baml_options__?: { tb?: TypeBuilder, clientRegistry?: ClientRegistry }
  ): BamlStream<(partial_types.MissingParam | null)[], MissingParam[]> {
    try {
      const raw = this.runtime.streamFunction(
        "GetMissingParams",
        {
          "params": params,"analysis": analysis
        },
        undefined,
        this.ctx_manager.cloneContext(),
        __baml_options__?.tb?.__tb(),
        __baml_options__?.clientRegistry,
      )
      return new BamlStream<(partial_types.MissingParam | null)[], MissingParam[]>(
        raw,
        (a): (partial_types.MissingParam | null)[] => a,
        (a): MissingParam[] => a,
        this.ctx_manager.cloneContext(),
      )
    } catch (error) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)