/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Analysis,  CashFlow,  CostOfRevenue,  Costs,  Deltas,  EBITDA,  Expenses,  Experience,  FinancialMetrics,  FinancialMetricsEBITDA,  Formula,  GrossProfit,  MissingParam,  MonthlyComparison,  Name,  PerShare,  Profitability,  ProformaMetrics,  Resume,  Revenue } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
    value: T
    state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    
    export interface Analysis {
        keyAssumptions?: (Record<string, ((number | null) | (string | null) | null)> | null)
        metric_type?: ("proforma" | "monthly" | null)
        proformaMetrics: ((partial_types.ProformaMetrics | null)[] | null)
        monthlyMetrics: ((partial_types.MonthlyComparison | null)[] | null)
        formulas?: (partial_types.Formula | null)[]
    }
    
    export interface CashFlow {
        operating?: (number | null)
        investing?: (number | null)
        financing?: (number | null)
        netChange?: (number | null)
    }
    
    export interface CostOfRevenue {
        support?: (number | null)
        hostingAndDelivery?: (number | null)
        total?: (number | null)
    }
    
    export interface Costs {
        productCosts?: (number | null)
        serviceCosts?: (number | null)
        totalCosts?: (number | null)
        researchAndDevelopment?: (number | null)
        salesAndMarketing?: (number | null)
        generalAndAdmin?: (number | null)
        impairmentAndRestructuring?: (number | null)
    }
    
    export interface Deltas {
        arr?: (number | null)
        revenue?: (number | null)
        netIncome?: (number | null)
        bankBalance?: (number | null)
    }
    
    export interface EBITDA {
        depreciation?: (number | null)
        amortization?: (number | null)
        interestExpense?: (number | null)
        ebitdaValue?: (number | null)
        ebitdaMargin?: (number | null)
    }
    
    export interface Expenses {
        engineering?: (number | null)
        generalAndAdmin?: (number | null)
        salesAndMarketing?: (number | null)
        total?: (number | null)
    }
    
    export interface Experience {
        role?: (string | null)
        company?: (string | null)
    }
    
    export interface FinancialMetrics {
        arr?: (number | null)
        revenue?: (number | null)
        costOfRevenue?: (partial_types.CostOfRevenue | null)
        grossProfit: ((partial_types.GrossProfit | null) | null)
        expenses?: (partial_types.Expenses | null)
        netIncome?: (number | null)
        cashFlow?: (partial_types.CashFlow | null)
        bankBalance?: (number | null)
    }
    
    export interface FinancialMetricsEBITDA {
        year?: (string | null)
        revenue: ((partial_types.Revenue | null) | null)
        costs: ((partial_types.Costs | null) | null)
        profitability: ((partial_types.Profitability | null) | null)
        perShare: ((partial_types.PerShare | null) | null)
        ebitda: ((partial_types.EBITDA | null) | null)
    }
    
    export interface Formula {
        name?: (string | null)
        purpose?: (string | null)
        parameters?: (string | null)[]
        expression?: (string | null)
    }
    
    export interface GrossProfit {
        amount?: (number | null)
        margin?: (number | null)
    }
    
    export interface MissingParam {
        name?: (string | null)
        formula?: (partial_types.Formula | null)
    }
    
    export interface MonthlyComparison {
        month?: (string | null)
        target: ((partial_types.FinancialMetrics | null) | null)
        actual?: (partial_types.FinancialMetrics | null)
        deltas?: (partial_types.Deltas | null)
    }
    
    export interface Name {
        first?: (string | null)
        last?: (string | null)
    }
    
    export interface PerShare {
        basic?: (number | null)
        diluted?: (number | null)
    }
    
    export interface Profitability {
        grossMargin?: (number | null)
        operatingIncome?: (number | null)
        otherIncome?: (number | null)
        incomeTaxes?: (number | null)
        netIncome?: (number | null)
    }
    
    export interface ProformaMetrics {
        period?: (string | null)
        effectiveGrossRevenue?: (number | null)
        operatingExpenses?: (number | null)
        netOperatingIncome: ((number | null) | null)
        capitalExpenditures: ((number | null) | null)
        cashFlowFromOperations: ((number | null) | null)
        capRate: ((number | null) | null)
        propertyValue: ((number | null) | null)
        valuePerUnit: ((number | null) | null)
        yieldOnCost: ((number | null) | null)
        totalProjectCost: ((number | null) | null)
        developmentSpread: ((number | null) | null)
    }
    
    export interface Resume {
        name?: (partial_types.Name | null)
        email?: (string | null)
        experience?: (string | null)[]
        skills?: (string | null)[]
    }
    
    export interface Revenue {
        product?: (number | null)
        serviceAndOther?: (number | null)
        total?: (number | null)
    }
    
}