/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
import type { Image, Audio } from "@boundaryml/baml"

/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export interface Analysis {
  keyAssumptions: Record<string, number | string>
  metric_type: "proforma" | "monthly"
  proformaMetrics?: ProformaMetrics[] | null
  monthlyMetrics?: MonthlyComparison[] | null
  formulas: Formula[]
  
}

export interface CashFlow {
  operating: number
  investing: number
  financing: number
  netChange: number
  
}

export interface CostOfRevenue {
  support: number
  hostingAndDelivery: number
  total: number
  
}

export interface Costs {
  productCosts: number
  serviceCosts: number
  totalCosts: number
  researchAndDevelopment: number
  salesAndMarketing: number
  generalAndAdmin: number
  impairmentAndRestructuring: number
  
}

export interface Deltas {
  arr: number
  revenue: number
  netIncome: number
  bankBalance: number
  
}

export interface EBITDA {
  depreciation: number
  amortization: number
  interestExpense: number
  ebitdaValue: number
  ebitdaMargin: number
  
}

export interface Expenses {
  engineering: number
  generalAndAdmin: number
  salesAndMarketing: number
  total: number
  
}

export interface Experience {
  role: string
  company: string
  
}

export interface FinancialMetrics {
  arr: number
  revenue: number
  costOfRevenue: CostOfRevenue
  grossProfit?: GrossProfit | null
  expenses: Expenses
  netIncome: number
  cashFlow: CashFlow
  bankBalance: number
  
}

export interface FinancialMetricsEBITDA {
  year: string
  revenue?: Revenue | null
  costs?: Costs | null
  profitability?: Profitability | null
  perShare?: PerShare | null
  ebitda?: EBITDA | null
  
}

export interface Formula {
  name: string
  purpose: string
  parameters: string[]
  expression: string
  
}

export interface GrossProfit {
  amount: number
  margin: number
  
}

export interface MissingParam {
  name: string
  formula: Formula
  
}

export interface MonthlyComparison {
  month: string
  target?: FinancialMetrics | null
  actual: FinancialMetrics
  deltas: Deltas
  
}

export interface Name {
  first: string
  last: string
  
}

export interface PerShare {
  basic: number
  diluted: number
  
}

export interface Profitability {
  grossMargin: number
  operatingIncome: number
  otherIncome: number
  incomeTaxes: number
  netIncome: number
  
}

export interface ProformaMetrics {
  period: string
  effectiveGrossRevenue: number
  operatingExpenses: number
  netOperatingIncome?: number | null
  capitalExpenditures?: number | null
  cashFlowFromOperations?: number | null
  capRate?: number | null
  propertyValue?: number | null
  valuePerUnit?: number | null
  yieldOnCost?: number | null
  totalProjectCost?: number | null
  developmentSpread?: number | null
  
}

export interface Resume {
  name: Name
  email: string
  experience: string[]
  skills: string[]
  
}

export interface Revenue {
  product: number
  serviceAndOther: number
  total: number
  
}
